#!/usr/bin/env bash

KIEX_HOME="$HOME/.kiex"
KIEX_BIN_PATH="$KIEX_HOME/bin/kiex"
KIEX_SCRIPTS_PATH="$KIEX_HOME/scripts"

SYSTEM=$(uname -s)

if [ "$SYSTEM" = "Linux" ] ; then
  if [ -n "$(which lsb_release 2> /dev/null)" ] ; then
    lsb_id=$(lsb_release -s -i)
    case $lsb_id in
      Ubuntu) DISTRO="Ubuntu" ;;
      Centos) DISTRO="Centos" ;;
      Gentoo) DISTRO="Gentoo" ;;
      Arch)   DISTRO="Arch" ;;
      Fedora) DISTRO="Fedora" ;;
      *) DISTRO="$lsb_id" ;;
    esac
  elif [ "$(grep -ic Ubuntu /etc/issue)" = 1 ] ; then
    DISTRO="Ubuntu"
  elif [ "$(grep -ic Centos /etc/issue)" = 1 ] ; then
    DISTRO=Centos
  elif [ "$([[ -f /etc/inittab ]] && grep -ic Gentoo /etc/inittab)" = 3 ] ; then
    DISTRO=Gentoo
  else
    echo "Unknown Linux distribution"
  fi
elif [ "$SYSTEM" = "FreeBSD" ] ; then
  DISTRO=FreeBSD
elif [ "$SYSTEM" = "Darwin" ] ; then
  #DISTRO=$(uname -r)
  DISTRO=OSX
else
  echo "Unsupported system $SYSTEM"
  exit 1
fi

# REALKIEX=$(which kiex > /dev/null 2>&1)
# if [ "$?" = 0 ] ; then
#   UPGRADE=1
# else
#   UPGRADE=0
# fi


UPGRADE=0
UPDATE=0
if [ "$1" = "upgrade" -a -f "$KIEX_HOME/bin/kiex" ] ; then
  UPGRADE=1
elif [ "$1" = "update" -a -f "$KIEX_HOME/bin/kiex" ] ; then
  UPDATE=1
fi

mkdir -p "$KIEX_HOME/"{bin,builds,elixirs,scripts}
curl -qs -o "$KIEX_HOME/bin/kiex" https://raw.githubusercontent.com/taylor/kiex/master/kiex
chmod +x "$KIEX_HOME/bin/kiex"
#echo "$KIEX_HOME/bin/kiex" setup
if [ $UPDATE = 1 ] ; then
  exec "$KIEX_HOME/bin/kiex" selfupdate
  #exec "$KIEX_HOME/bin/kiex" setup update
elif [ $UPGRADE = 1 ] ; then
  exec "$KIEX_HOME/bin/kiex" setup upgrade
else
  echo "Running initial environment setup"
  exec "$KIEX_HOME/bin/kiex" setup
fi

# function create_kiex_env_script() {
#   cat <<"EOF"> "$KIEX_SCRIPTS_PATH/kiex"
# KIEX_HOME="$HOME/.kiex"
# export PATH=$KIEX_HOME/bin:$PATH
# [[ -f $KIEX_HOME/elixirs/.default ]] && source $KIEX_HOME/elixirs/.default
# EOF
# }
#
# create_kiex_env_script
#
#echo "kiex has been installed in $KIEX_HOME"
#echo "Add the following to your shell's config file (.bashrc/.zshrc):"
#echo "    [[ -s \"\$HOME/.kiex/scripts/kiex\" ]] && source \"\$HOME/.kiex/scripts/kiex\""
